# Generated by Django 6.1 on 2026-09-03 13:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='university_logos/')),
                ('description', models.TextField(blank=True, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('full', 'Full Scholarship'), ('partial', 'Partial Scholarship'), ('tuition', 'Tuition Fee Waiver'), ('living', 'Living Stipend'), ('research', 'Research Grant'), ('other', 'Other')], default='full', max_length=20)),
                ('level', models.CharField(choices=[('bachelor', 'Bachelor'), ('master', 'Master'), ('phd', 'PhD'), ('postdoc', 'Postdoctoral'), ('exchange', 'Exchange Program'), ('summer', 'Summer School'), ('other', 'Other')], default='bachelor', max_length=20)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, help_text='Scholarship amount in USD', max_digits=12, null=True)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('duration', models.CharField(blank=True, help_text='e.g., 1 year, 4 years, etc.', max_length=100, null=True)),
                ('application_deadline', models.DateTimeField()),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('eligibility_criteria', models.TextField(help_text='List eligibility requirements')),
                ('required_education_level', models.CharField(blank=True, max_length=100, null=True)),
                ('minimum_gpa', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('required_fields_of_study', models.JSONField(blank=True, default=list, help_text='List of accepted fields of study')),
                ('application_fee', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('application_link', models.URLField(blank=True, help_text='Link to apply', null=True)),
                ('required_documents', models.JSONField(blank=True, default=list, help_text='List of required documents')),
                ('application_instructions', models.TextField(blank=True, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('language', models.CharField(default='English', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scholarships', to='scholarships.university')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
