# Generated by Django 6.1 on 2026-09-25 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='founding_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='motto',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
