# Generated by Django 6.1 on 2026-09-25 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0003_university_latitude_university_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campuslandmark',
            name='category',
            field=models.CharField(choices=[('academic', 'Academic Building'), ('gate', 'Gate & Entrance'), ('nature', 'Nature & Scenery'), ('life', 'Campus Life'), ('dining', 'Canteen & Dining'), ('sports', 'Sports & Activities'), ('culture', 'Culture & Museum')], default='academic', max_length=20),
        ),
    ]
