# Generated by Django 6.1 on 2026-09-26 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0004_campuslandmark_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarship',
            name='tuition_info',
            field=models.TextField(blank=True, help_text='Published tuition fees per year (RMB) by program level', null=True),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='level',
            field=models.CharField(choices=[('bachelor', 'Bachelor'), ('master', 'Master'), ('phd', 'PhD'), ('postdoc', 'Postdoctoral'), ('exchange', 'Exchange Program'), ('summer', 'Summer School'), ('other', 'Other'), ('all', 'All Levels')], default='bachelor', max_length=20),
        ),
    ]
