# Generated by Django 6.1 on 2026-09-26 03:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0005_scholarship_tuition_info_alter_scholarship_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('date', models.DateField(blank=True, null=True)),
                ('url', models.URLField(blank=True, max_length=1000, null=True)),
                ('kind', models.CharField(choices=[('brochure', 'Admission Brochure'), ('guide', 'Program Guide'), ('notice', 'Admission Notice'), ('scholarship', 'Scholarship Notice'), ('qa', 'Q&A')], default='notice', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='scholarships.university')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('university', 'title')},
            },
        ),
    ]
