# Generated by Django 6.1 on 2026-09-26 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0006_admissionannouncement'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarship',
            name='seats_filled',
            field=models.PositiveIntegerField(default=0, help_text='Places already taken'),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='total_seats',
            field=models.PositiveIntegerField(default=0, help_text='Total places for this scholarship (0 = unknown)'),
        ),
    ]
