# Generated by Django 6.1 on 2026-09-26 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0007_scholarship_seats_filled_scholarship_total_seats'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='about',
            field=models.TextField(blank=True, help_text='4-5 paragraph background (e.g. from Wikipedia)', null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='wikipedia_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
