# Generated by Django 6.1 on 2026-09-26 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0008_university_about_university_wikipedia_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='about_ar',
            field=models.TextField(blank=True, help_text='Native Arabic background from Arabic Wikipedia', null=True),
        ),
    ]
