# Generated by Django 6.1 on 2026-09-16 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='premium_expiry_date',
        ),
        migrations.RemoveField(
            model_name='student',
            name='premium_payment_id',
        ),
        migrations.RemoveField(
            model_name='student',
            name='premium_start_date',
        ),
        migrations.RemoveField(
            model_name='student',
            name='premium_type',
        ),
        migrations.AddField(
            model_name='student',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='payment_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
