from django.core.management.base import BaseCommand
from scholarships.models import University


class Command(BaseCommand):
    help = 'Update university websites with real URLs'

    def handle(self, *args, **options):
        websites = {
            'Tsinghua University': 'https://www.tsinghua.edu.cn/en/',
            'Peking University': 'https://www.pku.edu.cn/',
            'Fudan University': 'https://www.fudan.edu.cn/en/',
            'Shanghai Jiao Tong University': 'https://www.sjtu.edu.cn/',
            'Zhejiang University': 'https://www.zju.edu.cn/english/',
            'University of Science and Technology of China': 'https://www.ustc.edu.cn/english/',
            'USTC': 'https://www.ustc.edu.cn/english/',
            'Nanjing University': 'https://www.nju.edu.cn/english/',
            'Wuhan University': 'https://www.whu.edu.cn/',
            'Huazhong University of Science and Technology': 'https://english.hust.edu.cn/',
            'HUST': 'https://english.hust.edu.cn/',
            'Sun Yat-sen University': 'https://www.sysu.edu.cn/english/',
            'Harbin Institute of Technology': 'https://www.hit.edu.cn/',
            'HIT': 'https://www.hit.edu.cn/',
            'Beihang University': 'https://www.buaa.edu.cn/',
            'Beijing Normal University': 'https://www.bnu.edu.cn/',
            'Tongji University': 'https://www.tongji.edu.cn/english/',
            'Sichuan University': 'https://www.scu.edu.cn/',
            'Shandong University': 'https://www.sdu.edu.cn/',
            'Xi\'an Jiaotong University': 'https://en.xjtu.edu.cn/',
            'Jilin University': 'https://www.jlu.edu.cn/',
            'Nankai University': 'https://www.nankai.edu.cn/',
            'Tianjin University': 'https://www.tju.edu.cn/',
            'Dalian University of Technology': 'https://www.dlut.edu.cn/',
            'East China Normal University': 'https://www.ecnu.edu.cn/',
            'ECNU': 'https://www.ecnu.edu.cn/',
            'Xiamen University': 'https://www.xmu.edu.cn/',
            'Beijing Institute of Technology': 'https://www.bit.edu.cn/',
            'China Agricultural University': 'https://www.cau.edu.cn/',
            'Central South University': 'https://www.csu.edu.cn/',
            'Lanzhou University': 'https://www.lzu.edu.cn/',
            'Southwest Jiaotong University': 'https://www.swjtu.edu.cn/',
            'Hunan University': 'https://www.hnu.edu.cn/',
            'Chongqing University': 'https://www.cqu.edu.cn/',
            'Southeast University': 'https://www.seu.edu.cn/',
            'Jinan University': 'https://www.jnu.edu.cn/',
            'Soochow University': 'https://www.suda.edu.cn/',
            'Qingdao University': 'https://www.qdu.edu.cn/',
            'Yunnan University': 'https://www.ynu.edu.cn/',
            'Shanghai University': 'https://www.shu.edu.cn/',
            'Wuhan University of Technology': 'https://www.whut.edu.cn/',
            'WHUT': 'https://www.whut.edu.cn/',
            'China University of Geosciences': 'https://www.cug.edu.cn/',
            'CUGB': 'https://www.cugb.edu.cn/',
            'China University of Petroleum': 'https://www.upc.edu.cn/',
            'Beijing University of Chemical Technology': 'https://www.buct.edu.cn/',
            'Nanjing University of Science and Technology': 'https://www.njust.edu.cn/',
            'NJUST': 'https://www.njust.edu.cn/',
            'Nanjing University of Posts and Telecommunications': 'https://www.njupt.edu.cn/',
            'NJUPT': 'https://www.njupt.edu.cn/',
            'Hohai University': 'https://www.hhu.edu.cn/',
            'Nanjing Normal University': 'https://www.njnu.edu.cn/',
            'NNU': 'https://www.njnu.edu.cn/',
            'China University of Mining and Technology': 'https://www.cumt.edu.cn/',
            'University of Electronic Science and Technology of China': 'https://www.uestc.edu.cn/',
            'UESTC': 'https://www.uestc.edu.cn/',
            'Southwest University of Finance and Economics': 'https://www.swufe.edu.cn/',
            'SUFE': 'https://www.swufe.edu.cn/',
            'Chengdu University of Technology': 'https://www.cdut.edu.cn/',
            'CDUT': 'https://www.cdut.edu.cn/',
            'Northeast Forestry University': 'https://www.nefu.edu.cn/',
            'NEFU': 'https://www.nefu.edu.cn/',
            'Heilongjiang University': 'https://www.hlju.edu.cn/',
            'HLJU': 'https://www.hlju.edu.cn/',
            'Northwestern Polytechnical University': 'https://www.nwpu.edu.cn/',
            'NPU': 'https://www.nwpu.edu.cn/',
            'Northwest A&F University': 'https://www.nwafu.edu.cn/',
            'NWAFU': 'https://www.nwafu.edu.cn/',
            'Beijing Foreign Studies University': 'https://www.bfsu.edu.cn/',
            'BFSU': 'https://www.bfsu.edu.cn/',
            'Central University of Finance and Economics': 'https://www.cufe.edu.cn/',
            'CUFE': 'https://www.cufe.edu.cn/',
            'Beijing Language and Culture University': 'https://www.blcu.edu.cn/',
            'BLCU': 'https://www.blcu.edu.cn/',
            'Beijing International Studies University': 'https://www.bisu.edu.cn/',
            'BISU': 'https://www.bisu.edu.cn%',
            'Shanghai International Studies University': 'https://www.shisu.edu.cn/',
            'SISU': 'https://www.shisu.edu.cn/',
            'Donghua University': 'https://www.dhu.edu.cn/',
            'Shanghai Maritime University': 'https://www.shmtu.edu.cn/',
            'South China University of Technology': 'https://www2.scut.edu.cn/',
            'SCUT': 'https://www2.scut.edu.cn/',
            'South China Normal University': 'https://www.scnu.edu.cn/',
            'SCNU': 'https://www.scnu.edu.cn%',
            'Guangdong University of Technology': 'https://www.gdut.edu.cn/',
            'GDUT': 'https://www.gdut.edu.cn/',
            'Guangdong Medical University': 'https://www.gdmu.edu.cn/',
            'GMU': 'https://www.gdmu.edu.cn/',
            'Guangdong University of Foreign Studies': 'https://www.gdufs.edu.cn/',
            'GDUFS': 'https://www.gdufs.edu.cn%',
            'UCAS': 'https://www.ucas.ac.cn/',
            'China Scholarship Council': 'https://www.csc.edu.cn/',
            'Various Chinese Universities': '',
            'scholars4dev.com': 'https://www.scholars4dev.com/',
            'Beijing Jiaotong University': 'https://www.njtu.edu.cn/',
            'Beijing University of Technology': 'https://www.bjut.edu.cn/',
            'Capital Medical University': 'https://www.ccmu.edu.cn/',
            'Shanghai Tech University': 'https://www.shanghaitech.edu.cn/',
            'Beijing University of Posts and Telecommunications': 'https://www.bupt.edu.cn/',
            'University of International Business and Economics': 'https://www.uibe.edu.cn/',
            'Renmin University of China': 'https://www.ruc.edu.cn/',
            'Beijing University of Chinese Medicine': 'https://www.bucm.edu.cn/',
            'Minzu University of China': 'https://www.muc.edu.cn/',
            'Beijing Forestry University': 'https://www.bjfu.edu.cn/',
            'Beijing Sport University': 'https://www.bsu.edu.cn/',
            'Beijing University of Civil Engineering and Architecture': 'https://www.bucea.edu.cn/',
            'Capital Normal University': 'https://www.cnu.edu.cn/',
            'Shanghai University of Finance and Economics': 'https://www.shufe.edu.cn/',
            'China Pharmaceutical University': 'https://www.cpu.edu.cn/',
            'Nanjing Agricultural University': 'https://www.njau.edu.cn/',
            'Nanjing Forestry University': 'https://www.njfu.edu.cn/',
            'Jiangsu University': 'https://www.ujs.edu.cn/',
            'Suzhou University of Science and Technology': 'https://www.usts.edu.cn/',
            'Zhejiang University of Technology': 'https://www.zjut.edu.cn/',
            'Zhejiang University of Finance and Economics': 'https://www.zufe.edu.cn/',
            'Hangzhou Dianzi University': 'https://www.hdu.edu.cn%',
            'Fujian Agriculture and Forestry University': 'https://www.fafu.edu.cn%',
            'Fuzhou University': 'https://www.fzu.edu.cn%',
            'Xiangtan University': 'https://www.xtu.edu.cn%',
            'Central South University of Forestry and Technology': 'https://www.csuft.edu.cn%',
            'Zhongnan University of Economics and Law': 'https://www.zuel.edu.cn%',
            'ZUEL': 'https://www.zuel.edu.cn%',
            'Shanghai Jiao Tong University School of Medicine': 'https://www.shsmu.edu.cn%',
            'Third Military Medical University': 'https://www.tmmu.edu.cn%',
            'Second Military Medical University': 'https://www.smmu.edu.cn%',
            'Xinjiang University': 'https://www.xju.edu.cn%',
            'Tibet University': 'https://www.uot.edu.cn%',
            'Ningxia University': 'https://www.nxu.edu.cn%',
            'Hainan University': 'https://www.hainanu.edu.cn%',
            'Guizhou University': 'https://www.gzu.edu.cn%',
            'Inner Mongolia University': 'https://www.imu.edu.cn%',
            'Guangxi University': 'https://www.gxu.edu.cn%',
            'Yunnan Normal University': 'https://www.ynnu.edu.cn%',
            'Harbin Engineering University': 'https://www.heu.edu.cn%',
            'Hebei University of Technology': 'https://www.hebut.edu.cn%',
            'Henan University': 'https://www.henu.edu.cn%',
            'Anhui University': 'https://www.ahu.edu.cn%',
            'Jiangxi Normal University': 'https://www.jxnu.edu.cn%',
        }

        updated = 0
        for name, url in websites.items():
            try:
                uni = University.objects.get(name=name)
                if url and not uni.website:
                    uni.website = url
                    uni.save()
                    updated += 1
                    self.stdout.write(f'  Updated: {name} -> {url}')
            except University.DoesNotExist:
                self.stdout.write(f'  Not found: {name}')

        # Also fix any trailing % characters
        for uni in University.objects.all():
            if uni.website and uni.website.endswith('%'):
                uni.website = uni.website.rstrip('%')
                uni.save()
                self.stdout.write(f'  Fixed URL: {uni.name} -> {uni.website}')

        self.stdout.write(self.style.SUCCESS(f'\nDone! Updated {updated} universities'))
