# Generated by Django 6.1 on 2026-09-13 13:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scholarships', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=64)),
                ('role', models.CharField(choices=[('user', 'Student'), ('assistant', 'AI Assistant'), ('system', 'System')], max_length=10)),
                ('message', models.TextField()),
                ('intent', models.CharField(blank=True, help_text='Detected intent: scholarship_search, document_help, deadline, eligibility, etc.', max_length=50, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='AISuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggestion_type', models.CharField(choices=[('deadline_approaching', 'Deadline Approaching'), ('new_scholarship', 'New Matching Scholarship'), ('document_reminder', 'Document Reminder'), ('tip', 'Application Tip'), ('warning', 'Warning / Issue'), ('recommendation', 'Personalized Recommendation')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('is_dismissed', models.BooleanField(default=False)),
                ('action_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('related_scholarship', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_suggestions', to='scholarships.scholarship')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_suggestions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScholarshipVerificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_url', models.URLField()),
                ('status', models.CharField(choices=[('active', 'Active / Link Working'), ('broken', 'Broken Link'), ('expired', 'Expired Deadline'), ('redirected', 'Redirected'), ('unreachable', 'Unreachable'), ('deactivated', 'Auto-Deactivated')], max_length=20)),
                ('http_status_code', models.PositiveIntegerField(blank=True, null=True)),
                ('response_time_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('redirect_url', models.URLField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('checked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('action_taken', models.TextField(blank=True, help_text='What the system did in response (e.g., deactivated listing)', null=True)),
                ('scholarship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_logs', to='scholarships.scholarship')),
            ],
            options={
                'ordering': ['-checked_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_step', models.CharField(choices=[('discovered', 'Discovered'), ('researching', 'Researching Requirements'), ('documents_gathering', 'Gathering Documents'), ('documents_complete', 'Documents Ready'), ('writing_motivation', 'Writing Motivation Letter'), ('writing_complete', 'Motivation Letter Done'), ('getting_recommendations', 'Getting Recommendation Letters'), ('recommendations_complete', 'Recommendations Done'), ('submitting', 'Submitting Application'), ('submitted', 'Application Submitted'), ('interview_prep', 'Interview Preparation'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('enrolled', 'Enrolled')], default='discovered', max_length=30)),
                ('checklist', models.JSONField(blank=True, default=dict, help_text='Per-step checklist: {"documents_gathering": {"transcript": false, "passport": true, ...}}')),
                ('ai_recommendations', models.JSONField(blank=True, default=list, help_text='AI-generated tips/next steps for this application')),
                ('notes', models.TextField(blank=True, null=True)),
                ('deadline_reminder_sent', models.BooleanField(default=False)),
                ('last_ai_check', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scholarship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracked_applications', to='scholarships.scholarship')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_tracker', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('student', 'scholarship')},
            },
        ),
        migrations.CreateModel(
            name='ScholarshipMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_score', models.PositiveIntegerField(help_text='0-100 score indicating how well the scholarship matches the student profile')),
                ('match_reasons', models.JSONField(blank=True, default=list, help_text='List of reasons why this scholarship matches')),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('scholarship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='scholarships.scholarship')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scholarship_matches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-match_score'],
                'unique_together': {('student', 'scholarship')},
            },
        ),
    ]
