# Generated by Django 6.1 on 2026-09-13 14:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScraperSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('source_type', models.CharField(choices=[('generic', 'Generic URL Scraper'), ('portal', 'Scholarship Portal'), ('university', 'University Website'), ('api', 'API Endpoint')], default='generic', max_length=50)),
                ('is_enabled', models.BooleanField(default=True)),
                ('last_scraped', models.DateTimeField(blank=True, null=True)),
                ('total_found', models.PositiveIntegerField(default=0)),
                ('total_created', models.PositiveIntegerField(default=0)),
                ('scrape_interval_hours', models.PositiveIntegerField(default=24)),
                ('config', models.JSONField(blank=True, default=dict, help_text='Extra config for custom scrapers')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ScraperLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('success', 'Success'), ('partial', 'Partial Success'), ('failed', 'Failed')], max_length=20)),
                ('scholarships_found', models.PositiveIntegerField(default=0)),
                ('scholarships_created', models.PositiveIntegerField(default=0)),
                ('scholarships_skipped', models.PositiveIntegerField(default=0)),
                ('errors_count', models.PositiveIntegerField(default=0)),
                ('error_details', models.TextField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='scholarship_scraper.scrapersource')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
